# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: stubs/|venv/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-json
    -   id: detect-private-key
    -   id: mixed-line-ending


-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: "./precommit_mypy"
        language: python
        additional_dependencies: ["mypy"]
        # trigger for commits changing Python files
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # print the number of files as a sanity-check
        #verbose: true


-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
    -   id: python-no-log-warn


# -   repo: https://github.com/asottile/add-trailing-comma
#     rev: v2.2.3
#     hooks:
#     -   id: add-trailing-comma
#         args: [--py36-plus]


-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]


-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4' # Update me!
    hooks:
    -   id: bandit
        args: [--quiet, -c, bandit.yaml]
        exclude: __run_streamchatwars__\.py|tests/


-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: [-c]
