from ..voice import Voice as Voice
from collections.abc import Generator

def buildDriver(proxy): ...

class DummyDriver:
    def __init__(self, proxy) -> None: ...
    def destroy(self) -> None: ...
    def startLoop(self) -> None: ...
    def endLoop(self) -> None: ...
    def iterate(self) -> Generator[None, None, None]: ...
    def say(self, text) -> None: ...
    def stop(self) -> None: ...
    def getProperty(self, name): ...
    def setProperty(self, name, value): ...
