from . import fromUtf8 as fromUtf8, toUtf8 as toUtf8
from ..voice import Voice as Voice
from collections.abc import Generator

def buildDriver(proxy): ...

class EspeakDriver:
    def __init__(self, proxy) -> None: ...
    def numerise(self, data): ...
    def decode_numeric(self, data): ...
    def destroy(self) -> None: ...
    def say(self, text) -> None: ...
    def stop(self) -> None: ...
    def getProperty(self, name): ...
    def setProperty(self, name, value) -> None: ...
    def startLoop(self) -> None: ...
    def save_to_file(self, text, filename) -> None: ...
    def endLoop(self) -> None: ...
    def iterate(self) -> Generator[None, None, None]: ...
