from typing import Any

SPACE: str
TAB: str
RETURN: str
CARRIAGE_RETURN: str
WHITESPACE: Any
BEGIN_ARRAY: str
END_ARRAY: str
BEGIN_OBJECT: str
END_OBJECT: str
NAME_SEPARATOR: str
VALUE_SEPARATOR: str
CONTROL_CHARACTER: Any
QUOTATION_MARK: str
ESCAPE: str
