from ctypes import Structure, Union, c_ubyte
from enum import IntEnum, IntFlag
from typing import Any

c_byte = c_ubyte

class VIGEM_TARGET_TYPE(IntFlag):
    Xbox360Wired: int
    DualShock4Wired: int

class XUSB_BUTTON(IntFlag):
    XUSB_GAMEPAD_DPAD_UP: int
    XUSB_GAMEPAD_DPAD_DOWN: int
    XUSB_GAMEPAD_DPAD_LEFT: int
    XUSB_GAMEPAD_DPAD_RIGHT: int
    XUSB_GAMEPAD_START: int
    XUSB_GAMEPAD_BACK: int
    XUSB_GAMEPAD_LEFT_THUMB: int
    XUSB_GAMEPAD_RIGHT_THUMB: int
    XUSB_GAMEPAD_LEFT_SHOULDER: int
    XUSB_GAMEPAD_RIGHT_SHOULDER: int
    XUSB_GAMEPAD_GUIDE: int
    XUSB_GAMEPAD_A: int
    XUSB_GAMEPAD_B: int
    XUSB_GAMEPAD_X: int
    XUSB_GAMEPAD_Y: int

class XUSB_REPORT(Structure): ...
class DS4_LIGHTBAR_COLOR(Structure): ...

class DS4_BUTTONS(IntFlag):
    DS4_BUTTON_THUMB_RIGHT: Any
    DS4_BUTTON_THUMB_LEFT: Any
    DS4_BUTTON_OPTIONS: Any
    DS4_BUTTON_SHARE: Any
    DS4_BUTTON_TRIGGER_RIGHT: Any
    DS4_BUTTON_TRIGGER_LEFT: Any
    DS4_BUTTON_SHOULDER_RIGHT: Any
    DS4_BUTTON_SHOULDER_LEFT: Any
    DS4_BUTTON_TRIANGLE: Any
    DS4_BUTTON_CIRCLE: Any
    DS4_BUTTON_CROSS: Any
    DS4_BUTTON_SQUARE: Any

class DS4_SPECIAL_BUTTONS(IntFlag):
    DS4_SPECIAL_BUTTON_PS: Any
    DS4_SPECIAL_BUTTON_TOUCHPAD: Any

class DS4_DPAD_DIRECTIONS(IntEnum):
    DS4_BUTTON_DPAD_NONE: int
    DS4_BUTTON_DPAD_NORTHWEST: int
    DS4_BUTTON_DPAD_WEST: int
    DS4_BUTTON_DPAD_SOUTHWEST: int
    DS4_BUTTON_DPAD_SOUTH: int
    DS4_BUTTON_DPAD_SOUTHEAST: int
    DS4_BUTTON_DPAD_EAST: int
    DS4_BUTTON_DPAD_NORTHEAST: int
    DS4_BUTTON_DPAD_NORTH: int

class DS4_REPORT(Structure): ...

def DS4_SET_DPAD(report, dpad) -> None: ...
def DS4_REPORT_INIT(report) -> None: ...

class DS4_TOUCH(Structure): ...
class DS4_SUB_REPORT_EX(Structure): ...
class DS4_REPORT_EX(Union): ...

class VIGEM_ERRORS(IntEnum):
    VIGEM_ERROR_NONE: int
    VIGEM_ERROR_BUS_NOT_FOUND: int
    VIGEM_ERROR_NO_FREE_SLOT: int
    VIGEM_ERROR_INVALID_TARGET: int
    VIGEM_ERROR_REMOVAL_FAILED: int
    VIGEM_ERROR_ALREADY_CONNECTED: int
    VIGEM_ERROR_TARGET_UNINITIALIZED: int
    VIGEM_ERROR_TARGET_NOT_PLUGGED_IN: int
    VIGEM_ERROR_BUS_VERSION_MISMATCH: int
    VIGEM_ERROR_BUS_ACCESS_FAILED: int
    VIGEM_ERROR_CALLBACK_ALREADY_REGISTERED: int
    VIGEM_ERROR_CALLBACK_NOT_FOUND: int
    VIGEM_ERROR_BUS_ALREADY_CONNECTED: int
    VIGEM_ERROR_BUS_INVALID_HANDLE: int
    VIGEM_ERROR_XUSB_USERINDEX_OUT_OF_RANGE: int
    VIGEM_ERROR_INVALID_PARAMETER: int
    VIGEM_ERROR_NOT_SUPPORTED: int
