class FeatureSet:
    def __init__(self) -> None: ...
    def set(self, name, value: bool = ...) -> None: ...
    def remove(self, feature_name) -> None: ...
    def load(self, arguments) -> None: ...
    def load_feature(self, feature): ...

def string_int_pair(target, sep: str = ...): ...
